
services:
  db:
    image: mysql:8.4.0
    container_name: conference
    ports:
      - 3307:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: conference
    networks:
      - mysql-network

networks:
    mysql-network:
      name: mysql-network


